### ISSUE TITLE
Mac compatibility (Cannot connect to localhost)

### ISSUE THREAD

**Issue by robni7** [FitzgeraldKrudde/spotify-reverse-playlist#1]
Hi, I'm having trouble with this script. See terminal screenshot pasted below. When following the authorization link, the browser says it cannot connect to the server Localhost.

![Schermafbeelding 2020-12-25 om 16 56](https://user-images.githubusercontent.com/45372858/103138376-3f0fab00-46d2-11eb-885a-057c414e1e95.png)

**Comment by robni7** [comment]
Hey! I managed to make it work. Apparently some GNU commands do not translate 100% well into macOS, so I had to install a few compatible commands and replace them in the .sh file.

I installed through Brew the following packages: coreutils, findutils, jq.

Then used a slightly modified script, attached here: [https://gist.github.com/robni7/4e4de87552f8c66496981aa13e9da71e](https://gist.github.com/robni7/4e4de87552f8c66496981aa13e9da71e)

PS. I only tested it with `script.sh <playlist-id>`, so it may still be broken if you need to specify user-id or new-playlist-name/description. This was all I needed.

Cheers ;)

**Comment by FitzgeraldKrudde** [comment]
Hi,

Nice you got it working! I also have a Mac nowadays (what a crap when you're used to GNU/Linux..).

Well done, thanks for your contrib!
I will make a more Mac friendly version ;)

**Comment by kvdnberg** [comment]
@robni7 Thanks so much for sharing this. I tried the script after installing the packages you mentioned and I got very far but not quite all the way. In Safari after authorising I got an error it couldn't connect to localhost:8888/<etc> and the script gave the following output:

```After authorization this script will pickup the authorization code
Got authorization code:
failed with the following error:
invalid_request
exiting..```

If you have any ideas I'd love to hear from you.

**Comment by robni7** [comment]
I‘ll have a look sometime this week. I need to use this script exactly once a year (reverse the Top 2000 playlist), so it‘s not fresh in memory anymore. I‘ll keep this thread updated with my findings ;)

**Comment by kvdnberg** [comment]
Thanks @robni7! I have a small update, I tried it in Firefox instead of Safari because I noticed at the end of the error in Safari it said: "Because it is using HTTP/0.9". In FF it does seem to work better because I can now see the authorization code is passed to the script but then I get "invalid_client". From what I've found through Google it may be that the base64 encoding of the client secret is not url friendly? But I can't quite figure out how to fix that (yet)

If you're making a reverse for the NPO Radio 2 Top 2000, that's what I'm trying to do so sharing that list would be great too! I did find one for 2021 but it was missing a few songs. Happy Holidays!

**Comment by robni7** [comment]
Okay, so it turnt out a bit messy on my Mac, since I had to reinstall macOS (Sierra) a few weeks ago on my Mac Pro due to an unrelated hardware issue.

I made sure to install Xcode-utils and to reinstall the three formulae through Brew: coreutils (current version wouldn’t build on Sierra but I reinstated the files from a backup), findutils, and jq. Also I double checked the adapted GNU commands from the script I edited (linked in post no. 2).

For some reason, I would also get a localhost-related error in Safari, but it worked flawlessly through Firefox! So thanks for the tip, I would probably think of that step only much later.

Finally, the reversed Top 2000 link is here: [https://open.spotify.com/playlist/3a1to5pc1I2h9sS4JVUig9](https://open.spotify.com/playlist/3a1to5pc1I2h9sS4JVUig9). Cheers!

**Comment by kvdnberg** [comment]
@robni7 Thanks for the list! Excellent, listening now to parts I've missed already. I am on Monterey, Xcode utils is installed, I installed the three packages with brew without issues before I ran the script... so maybe it's a local issue or something to do with the MacOS version on my part. I may have another try sometime soon, just to see if I can make it work.

**Comment by FitzgeraldKrudde** [comment]
I was able to run the original script successfully!

I installed the brew packages **coreutils**, **findutils** and **jq** and made sure their directories were in front of my PATH by  adding this to my ${HOME}/.bashrc:
```
# add GNU coreutils and findutils in front of the PATH
export PATH=/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/findutils/libexec/gnubin:${PATH}
```

Regarding the browser: I am using Chrome. I am still on BigSur but I suspect this does not matter.

```
bash ./reverse-playlist.sh 72BOcumkj8jwxgo5HnXrOw 48y7i4dfky5goeqpio87rpl11
source_playlist_id: 72BOcumkj8jwxgo5HnXrOw
source_playlist_userid: 48y7i4dfky5goeqpio87rpl11
Go to this URL to authorize this script: <url>
After authorization this script will pickup the authorization code
Got authorization code: <code>
current_spotify_user: hlf28o2vqw2l59nn1gwkawl2e
#retrieved tracks: 100 200 300 400 500 600 700 800 900 1000 1100 1200 1300 1400 1500 1600 1700 1800 1900 2000 2002
#tracks_reversed: 2002
Created a new playlist (id: 246fBA9TOn1XdCMkFFT31k)
Adding 2002 tracks to the new playlist: .....................
Finished succesfully. URL of the (new) playlist: https://open.spotify.com/playlist/246fBA9TOn1XdCMkFFT31k
```

**Comment by FitzgeraldKrudde** [comment]
I think we can conclude the script also works on Mac. Closing this issue
