### ISSUE TITLE
"empty the current playlist (and add the reversed tracks)" is dangerous

### ISSUE THREAD

**Issue by cbruegg** [FitzgeraldKrudde/spotify-reverse-playlist#2]
I've just had the tool fail due to songs from local storage in my playlist. Since reversing failed, my playlist was completely wiped with no way to recover. The tool should probably default to creating a new playlist, always.

**Comment by robni7** [comment]
Not sure if it's possible in this case, but have you checked the playlist recovery tool in your account settings on spotify.com? Hopefully you'll be able to recover your list :)

**Comment by cbruegg** [comment]
Thanks a lot for the quick response 😃 Don’t worry, I disabled my phone’s data quickly enough to save the playlist’s songs manually. The online recovery didn’t offer me any options. 

I also might have a look at contributing a fix for this issue once I get time.

**Comment by cbruegg** [comment]
I've had a look at adapting the script, but didn't want to break its current behavior and command-line interface, so instead I've built another tool inspired by this one. For anyone curious, I've also made it open-source [here](https://github.com/cbruegg/spotify-playlist-reverser-kt). It's much more heavyweight than this bash script though, so it's probably not suitable for every use case.

**Comment by FitzgeraldKrudde** [comment]
Sorry for the late response. I agree with the statement that the default should be to create a new playlist. The risk of losing a playlist is not worth this optimisation (updating the original playlist). I am going to change this.

**Comment by FitzgeraldKrudde** [comment]
Fixed :-)
