### ISSUE TITLE
Basic questions

### ISSUE THREAD

**Issue by TomSonIQ** [FitzgeraldKrudde/spotify-reverse-playlist#3]
1. Does this script work for linux only or does it also work on windows/mac?
2. If it works on windows, how do I, as someone who has little experience with scripts and the likes, use it?

**Comment by rave14210** [comment]
Hi TomSonIQ, Today I was also puzzling with this Good that you put the question out here. The old outdate script previously here on Github always had a demo page through which you ccould right-away run the sript. This one sadly doesn't and would require the skill to run the script, which I also don't have.

If you're in a hurry: I found another workaround with Soundizz.com where I also platform-sync music playlists. I synced my existing playlist to another service (like Deezer, that recognized all songs) while doing this, there was a button to set/reverse the order. I then synced that playlist back from Deezer to a new one in Spotify, and voilá!

Cheers.

**Comment by FitzgeraldKrudde** [comment]
Hi TomSonIQ,

The script was build and targeted for Linux.
Mac might work (did not try).

Windows seems doubtful, you would probably need WSL and maybe some tweaks. I would welcome a PR ;)

**Comment by suppergerrie2** [comment]
I can confirm it works under WSL, only had to install jq.
To my surprise even authentication works immediatelly!

**Comment by FitzgeraldKrudde** [comment]
Thanks @suppergerrie2!

I will update the README with this info!
