### ISSUE TITLE
Limited to first 500 tracks

### ISSUE THREAD

**Issue by papagunit** [FitzgeraldKrudde/spotify-reverse-playlist#4]
Other than this bug, your script works like a charm!

The script correctly identified the number of tracks total (4,475), but Spotify did return the following:
```
{
  "status": 400,
  "message": "Invalid track uri: spotify:local:ABC:253"
}
```

But that wasn't the 500th track, so I don't think it's relevant, and the error is fine since the track is no longer available.

Curious if others are having this issue as well.

**Comment by FitzgeraldKrudde** [comment]
Can you please share the playlist you were processing. Then I can have look, and maybe improve the script (skip unknown tracks)

**Comment by papagunit** [comment]
Sure, the playlist is `https://open.spotify.com/playlist/6hcyZOyKI9Ouh5Rz8BkOVx?si=5241b59b10bb4a9c`

**Comment by FitzgeraldKrudde** [comment]
The cause was that the playlist contains local tracks which are apparently not supported by the Spotify API.
I made a fix to filter out the local tracks, see the latest commit.

I could then process the playlist succesfully

**Comment by papagunit** [comment]
I was thinking about forking this and configuring it so it will modify the same playlist each time, and then I can cron job it daily. However, I remembered the browser authentication, which can't really be automated. Any ideas on how to keep the authentication alive for subsequent runs? (obviously goes far beyond my knowledge of the spotify api)

**Comment by FitzgeraldKrudde** [comment]
The script used to work that way: if you reverse a playlist of your own it would empty it and add the reversed tracks.
In unhappy flows this was not nice as you could end up with an empty playlist...
Also now with this issue of local tracks you would loose them so I am happy the script now always creates a new playlist..

I do not know your use case exactly  but you could use 2 playlist files and use a symlink pointing to one of them. Then you could make crontab update the symlink

**Comment by papagunit** [comment]
I was thinking of adding an optional parameter to pass through the existing list id and then use it in the put request like you [had here](https://github.com/FitzgeraldKrudde/spotify-reverse-playlist/commit/dd3321c18b98e7dc4331a18b10a446ab34b2a9be).

But I had an even more clever idea, why not utilize the github actions, and [cron job it](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule) so that it can get updated everyday?

However, is there an authentication flow (other than implicit grant which requires authorization each time) that allows us to do that in a public repo?

**Comment by FitzgeraldKrudde** [comment]
Well, you might be able to use a refresh token but that would require periodic refreshes (I am not sure what the expiry period is)..
