### ISSUE TITLE
Netcat -p -l are mutually exclusive

### ISSUE THREAD

**Issue by Edeholland** [FitzgeraldKrudde/spotify-reverse-playlist#5]
I'm getting the following error when executing the script:
`nc: missing port with option -l`

According to [netcat](https://linux.die.net/man/1/nc) documentation, the -l and -p flags are mutually exclusive. It's probably safe to remove the -p flag and leave the port as is.

**Comment by FitzgeraldKrudde** [comment]
Thanks for the report!
Apparently there are forks of netcat...
My Linux distro (Gentoo) uses netcat from https://nc110.sourceforge.io/
Unfortunately the options are not compatible ..
Leaving out -p does not work for my netcat..

**Comment by Edeholland** [comment]
It looks like I am using the version that comes standard with MacOS, the BSD version. It doesn't even support `nc --version`, unfortunately. Might be a good idea to list it as a possible bug in the documentation. Closing the issue because it's not a bug in the script.

**Comment by FitzgeraldKrudde** [comment]
Actually it is already in the README: "On Mac you will need homebrew and install the following packages: coreutils, findutils and jq" :-)
